export type MuscleGroup =
  | "Chest" | "Back" | "Shoulders" | "Biceps" | "Triceps" | "Forearms"
  | "Legs" | "Glutes" | "Calves" | "Abs" | "Core" | "Full Body";

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest", "Back", "Shoulders", "Biceps", "Triceps", "Forearms",
  "Legs", "Glutes", "Calves", "Abs", "Core", "Full Body",
];

export type Difficulty = "beginner" | "intermediate" | "advanced";
export type Equipment =
  | "bodyweight" | "dumbbell" | "barbell" | "cable" | "machine" | "kettlebell" | "bands";

export const DIFFICULTIES: Difficulty[] = ["beginner", "intermediate", "advanced"];
export const EQUIPMENT: Equipment[] = [
  "bodyweight", "dumbbell", "barbell", "cable", "machine", "kettlebell", "bands",
];

export interface Exercise {
  name: string;
  muscle: MuscleGroup;
  secondary: string[];
  difficulty: Difficulty;
  equipment: Equipment;
  sets: number;
  reps: string;
  tip: string;             // short cue (legacy)
  instructions: string[];  // step-by-step
  mistakes: string[];      // common mistakes
  tips: string[];          // form correction tips
}

type ExArgs = [
  name: string,
  difficulty: Difficulty,
  equipment: Equipment,
  sets: number,
  reps: string,
  tip: string,
  instructions: string[],
  mistakes: string[],
  tips: string[],
  secondary?: string[],
];

const ex = (muscle: MuscleGroup) => (...a: ExArgs): Exercise => ({
  name: a[0], muscle, difficulty: a[1], equipment: a[2], sets: a[3], reps: a[4],
  tip: a[5], instructions: a[6], mistakes: a[7], tips: a[8], secondary: a[9] ?? [],
});

const C = ex("Chest");
const B = ex("Back");
const S = ex("Shoulders");
const Bi = ex("Biceps");
const Tr = ex("Triceps");
const Fa = ex("Forearms");
const L = ex("Legs");
const G = ex("Glutes");
const Ca = ex("Calves");
const A = ex("Abs");
const Co = ex("Core");
const FB = ex("Full Body");

const chest: Exercise[] = [
  C("Push-Ups", "beginner", "bodyweight", 4, "10-15", "Core tight, elbows ~45°.",
    ["Hands shoulder-width on floor", "Body straight line head to heels", "Lower chest to fist height", "Press up to lockout"],
    ["Sagging hips", "Flaring elbows wide", "Half range of motion"],
    ["Brace abs and glutes", "Tuck elbows ~45°", "Touch chest, not face"], ["Triceps","Shoulders"]),
  C("Incline Push-Ups", "beginner", "bodyweight", 3, "12-15", "Hands elevated reduces load.",
    ["Place hands on bench or step", "Plank position with straight body", "Lower until chest near surface", "Push back up"],
    ["Hips lifting up", "Partial reps"],
    ["Keep elbows under wrists", "Full range, full lockout"], ["Triceps"]),
  C("Decline Push-Ups", "intermediate", "bodyweight", 3, "10-12", "Feet elevated targets upper chest.",
    ["Feet on bench, hands on floor", "Strong plank", "Lower chest to ground", "Press up"],
    ["Letting head drop", "Elbows flaring 90°"],
    ["Look slightly forward", "Slow eccentric"], ["Shoulders"]),
  C("Diamond Push-Ups", "intermediate", "bodyweight", 3, "8-12", "Hands close, elbows tight.",
    ["Form diamond with thumbs/index fingers", "Plank position", "Lower chest to hands", "Press up"],
    ["Elbows flaring out", "Sagging hips"],
    ["Squeeze elbows to ribs", "Full lockout"], ["Triceps"]),
  C("Bench Press", "intermediate", "barbell", 4, "6-10", "Retract scapula, drive feet.",
    ["Lie on bench, grip just outside shoulders", "Unrack and lower to mid-chest", "Pause briefly", "Press to lockout"],
    ["Bouncing off chest", "Lifting hips", "Flared elbows 90°"],
    ["Pinch shoulder blades down and back", "Tuck elbows ~45°", "Drive heels into floor"], ["Triceps","Front Delts"]),
  C("Incline Bench Press", "intermediate", "barbell", 4, "6-10", "30–45° bench for upper chest.",
    ["Set bench to 30-45°", "Grip slightly wider than shoulders", "Lower to upper chest", "Press up smoothly"],
    ["Bench too steep (turns into shoulder)", "Bar drift toward face"],
    ["Bar path over upper chest", "Keep wrists stacked"], ["Front Delts","Triceps"]),
  C("Dumbbell Bench Press", "intermediate", "dumbbell", 4, "8-12", "Greater range than barbell.",
    ["Sit with DBs on thighs, kick back to bench", "Press up, palms forward", "Lower to chest level", "Press up, squeeze chest"],
    ["Banging DBs at top", "Locking elbows fully each rep"],
    ["Control descent 2 sec", "Stop just before lockout"], ["Triceps"]),
  C("Incline Dumbbell Press", "intermediate", "dumbbell", 3, "10-12", "Don't flare elbows.",
    ["Bench at 30°", "DBs at shoulder level", "Press up and slightly in", "Lower with control"],
    ["Elbows below bench plane", "Pressing forward only"],
    ["Light squeeze at top", "Elbows ~45° from torso"], ["Front Delts"]),
  C("Dumbbell Flyes", "intermediate", "dumbbell", 3, "10-15", "Slight elbow bend, hug a tree.",
    ["Lie flat, DBs above chest", "Arms slightly bent", "Lower DBs in wide arc", "Squeeze chest to return"],
    ["Locking out elbows", "Going too heavy and using press"],
    ["Imagine hugging a barrel", "Stop at chest level"], ["Front Delts"]),
  C("Cable Crossover", "intermediate", "cable", 3, "12-15", "Bring hands together in front.",
    ["Set pulleys high", "Step forward, slight lean", "Pull handles down and across", "Squeeze chest, return slow"],
    ["Bending arms too much", "Using momentum"],
    ["Maintain slight elbow bend", "Pause at peak contraction"], ["Front Delts"]),
  C("Chest Dips", "advanced", "bodyweight", 3, "8-12", "Lean forward, chest-focused.",
    ["Grip parallel bars, arms straight", "Lean torso forward 30°", "Lower until shoulders below elbows", "Press up"],
    ["Staying upright (triceps dominant)", "Shoulder shrugging"],
    ["Tuck chin slightly", "Control the descent"], ["Triceps","Front Delts"]),
  C("Machine Chest Press", "beginner", "machine", 3, "10-12", "Great for learning the pattern.",
    ["Adjust seat: handles at mid-chest", "Press forward smoothly", "Stop just before lockout", "Control back"],
    ["Shrugging shoulders up", "Partial range"],
    ["Pin shoulders to pad", "Full controlled range"], ["Triceps"]),
  C("Pec Deck", "beginner", "machine", 3, "12-15", "Isolation finisher.",
    ["Set arm pads at chest level", "Press pads together in arc", "Squeeze 1 sec", "Return slowly"],
    ["Heaving with body", "Hyperextending shoulders"],
    ["Keep back flat on pad", "Pause at peak"], []),
];

const back: Exercise[] = [
  B("Pull-Ups", "intermediate", "bodyweight", 4, "6-10", "Lead with chest.",
    ["Grip bar slightly wider than shoulders", "Hang with active shoulders", "Pull chest to bar", "Lower with control"],
    ["Kipping", "Half reps"],
    ["Drive elbows down", "Full hang each rep"], ["Biceps","Rear Delts"]),
  B("Chin-Ups", "intermediate", "bodyweight", 4, "6-10", "Underhand grip = more biceps.",
    ["Grip bar palms facing you", "Hang fully", "Pull until chin clears", "Lower slowly"],
    ["Swinging body", "Stopping short of chin"],
    ["Pull elbows to ribs", "Full ROM"], ["Biceps"]),
  B("Lat Pulldown", "beginner", "machine", 3, "10-12", "Squeeze blades down.",
    ["Sit and secure thighs", "Wide grip, slight back lean", "Pull bar to upper chest", "Resist on return"],
    ["Pulling behind neck", "Using only arms"],
    ["Lead with elbows", "Squeeze lats at bottom"], ["Biceps"]),
  B("Bent-Over Barbell Row", "intermediate", "barbell", 4, "8-10", "Neutral spine, pull to hip.",
    ["Hinge at hips, back flat", "Bar against shins", "Row to lower ribs/hip", "Lower under control"],
    ["Rounding lower back", "Yanking with arms", "Standing too upright"],
    ["Brace abs hard", "Elbows close to body"], ["Biceps","Rear Delts"]),
  B("Dumbbell Row", "beginner", "dumbbell", 3, "10-12", "Drive elbow to hip.",
    ["One knee/hand on bench", "Other arm holds DB", "Row DB to hip", "Lower fully"],
    ["Twisting torso", "Pulling with biceps only"],
    ["Pull elbow back, not up", "Pause at top"], ["Biceps"]),
  B("Seated Cable Row", "beginner", "cable", 3, "10-12", "Sit tall, retract shoulder blades.",
    ["Sit with feet braced", "Grip handle, arms extended", "Pull handle to lower ribs", "Slow return"],
    ["Leaning back excessively", "Rounding shoulders forward"],
    ["Chest up the whole time", "Squeeze blades at end"], ["Biceps"]),
  B("T-Bar Row", "intermediate", "barbell", 3, "8-10", "Hinged, dense back work.",
    ["Straddle bar, hinge over", "Grip handle, back flat", "Row to chest", "Lower with control"],
    ["Rounding spine", "Using too much momentum"],
    ["Set hips back", "Drive elbows behind body"], ["Biceps","Rear Delts"]),
  B("Inverted Row", "beginner", "bodyweight", 3, "8-12", "Body-weight horizontal pull.",
    ["Bar at hip height", "Hang under bar, body straight", "Pull chest to bar", "Lower with control"],
    ["Hips sagging", "Half pulling"],
    ["Plank-tight core", "Chest touches bar"], ["Biceps","Rear Delts"]),
  B("Face Pulls", "beginner", "cable", 3, "12-15", "Rope to forehead, elbows high.",
    ["Rope at face height", "Grip ropes, palms in", "Pull to forehead, elbows wide", "Return slowly"],
    ["Pulling low", "Shrugging shoulders up"],
    ["Lead elbows out", "Squeeze rear delts"], ["Rear Delts"]),
  B("Straight-Arm Pulldown", "intermediate", "cable", 3, "12-15", "Lat isolation, arms straight.",
    ["Bar high, slight forward lean", "Arms straight overhead", "Pull bar down to thighs", "Slow return"],
    ["Bending elbows", "Using torso"],
    ["Lock elbows lightly", "Initiate from lats"], []),
  B("Deadlift", "advanced", "barbell", 4, "5-8", "Hinge, brace, drive.",
    ["Bar over mid-foot, hinge to grip", "Shoulders over bar, back flat", "Push floor away, stand tall", "Lower with hips back"],
    ["Rounding lower back", "Bar drifts away", "Hyperextending at top"],
    ["Pull slack out of bar first", "Brace 360° before lift", "Stack ribs over hips at top"], ["Glutes","Hamstrings","Core"]),
  B("Rack Pulls", "intermediate", "barbell", 3, "6-8", "Partial deadlift from knee.",
    ["Bar at knee height", "Hinge to grip, flat back", "Drive hips through", "Lower to pins"],
    ["Jerking the bar", "Hyperextending lockout"],
    ["Treat as a deadlift top", "Lock glutes at top"], ["Glutes"]),
  B("Single-Arm Cable Row", "beginner", "cable", 3, "10-12", "Unilateral back work.",
    ["Single handle, kneel/seat", "Reach forward, then pull to hip", "Squeeze lat", "Slow return"],
    ["Twisting torso", "Short range"],
    ["Get full stretch and contraction", "Stay square to cable"], ["Biceps"]),
];

const shoulders: Exercise[] = [
  S("Overhead Press", "intermediate", "barbell", 4, "6-10", "Brace abs, don't arch.",
    ["Bar at shoulders, elbows under bar", "Brace core and glutes", "Press straight up", "Lower to clavicle"],
    ["Arching lower back", "Pressing forward, not up", "Flaring elbows wide"],
    ["Squeeze glutes", "Push head through at top", "Stack bar over mid-foot"], ["Triceps"]),
  S("Dumbbell Shoulder Press", "beginner", "dumbbell", 4, "8-12", "Seated or standing.",
    ["DBs at shoulder level, palms forward", "Press up, slight arc inward", "Stop before lockout", "Lower with control"],
    ["Banging DBs at top", "Hyperextending back"],
    ["Brace core tightly", "Wrists stacked over elbows"], ["Triceps"]),
  S("Arnold Press", "intermediate", "dumbbell", 3, "10-12", "Rotate palms during press.",
    ["DBs at shoulders, palms toward you", "Press and rotate palms out", "Lock at top, then reverse", "Control descent"],
    ["Going too heavy and skipping rotation", "Banging at top"],
    ["Smooth rotation", "Pause at bottom"], ["Triceps"]),
  S("Lateral Raises", "beginner", "dumbbell", 3, "12-15", "Slight bend, lead with elbows.",
    ["DBs at sides, slight elbow bend", "Raise arms out to shoulder height", "Pause briefly", "Lower slowly"],
    ["Swinging body", "Lifting with traps", "Going above shoulder"],
    ["Lead with elbows", "Pinky slightly up", "No momentum"], []),
  S("Front Raises", "beginner", "dumbbell", 3, "10-12", "Front delt isolation.",
    ["DBs at thighs, palms down", "Raise one (or both) to shoulder height", "Pause", "Lower with control"],
    ["Swinging hips", "Going above shoulder"],
    ["Squeeze front delts", "Arms nearly straight"], []),
  S("Bent-Over Rear Delt Fly", "intermediate", "dumbbell", 3, "12-15", "Hinge, fly out wide.",
    ["Hinge at hips, back flat", "DBs hang under shoulders", "Raise arms out to sides", "Lower slow"],
    ["Standing too upright", "Pulling with traps"],
    ["Lead with pinkies", "Squeeze rear delts hard"], ["Upper Back"]),
  S("Cable Lateral Raise", "intermediate", "cable", 3, "12-15", "Constant tension.",
    ["Cable at floor, handle in opposite hand", "Stand sideways, slight lean", "Raise arm to shoulder height", "Lower slow"],
    ["Using too much weight", "Twisting trunk"],
    ["Drive elbow up", "Keep wrist neutral"], []),
  S("Upright Row", "intermediate", "barbell", 3, "10-12", "Elbows lead, bar to chest.",
    ["Bar at thighs, narrow grip", "Pull bar to upper chest", "Elbows lead, above hands", "Lower slow"],
    ["Going too narrow", "Pulling past chin"],
    ["Shoulder-width grip is safer", "Stop at upper chest"], ["Traps"]),
  S("Face Pulls (Shoulders)", "beginner", "cable", 3, "15-20", "Healthy delts and rotators.",
    ["Rope at face height", "Pull to forehead, elbows high", "External rotate at end", "Return slow"],
    ["Going too heavy", "Dropping elbows"],
    ["External rotation cue: show your biceps", "Keep elbows above wrists"], ["Rotator Cuff"]),
  S("Pike Push-Ups", "intermediate", "bodyweight", 3, "8-12", "Body in inverted V.",
    ["Downward dog position", "Lower head toward floor", "Press back to start", "Keep hips high"],
    ["Hips dropping", "Half reps"],
    ["Walk feet closer = harder", "Elbows track over wrists"], ["Triceps"]),
  S("Machine Shoulder Press", "beginner", "machine", 3, "10-12", "Stable, beginner-friendly.",
    ["Adjust seat, handles at shoulders", "Press up smoothly", "Stop just shy of lockout", "Control descent"],
    ["Hyperextending back from pad", "Partial range"],
    ["Sit tall, back pressed in", "Full controlled range"], ["Triceps"]),
  S("Landmine Press", "intermediate", "barbell", 3, "8-12", "Shoulder-friendly press.",
    ["Stand at landmine bar end", "Press bar up and forward", "Slow eccentric", "Switch arms"],
    ["Leaning excessively", "Locking elbow hard"],
    ["Brace core to prevent lean", "Stack ribs over hips"], ["Triceps","Core"]),
];

const biceps: Exercise[] = [
  Bi("Barbell Curl", "beginner", "barbell", 4, "10-12", "Elbows pinned to sides.",
    ["Bar at thighs, shoulder-width grip", "Curl bar to shoulders", "Squeeze biceps", "Lower fully"],
    ["Swinging hips", "Lifting elbows forward"],
    ["Lock elbows at sides", "Full range, no half reps"], ["Forearms"]),
  Bi("Dumbbell Curl", "beginner", "dumbbell", 3, "10-12", "Alternating is fine.",
    ["DBs at sides, palms forward", "Curl one or both to shoulder", "Squeeze at top", "Lower fully"],
    ["Swinging", "Partial reps"],
    ["Pause at top 1 sec", "Slow eccentric 2 sec"], ["Forearms"]),
  Bi("Hammer Curls", "beginner", "dumbbell", 3, "10-12", "Neutral grip, brachialis.",
    ["DBs at sides, palms facing in", "Curl with neutral grip", "Squeeze", "Lower slow"],
    ["Swinging", "Going too heavy"],
    ["Elbows fixed", "Pause briefly at top"], ["Forearms","Brachialis"]),
  Bi("Incline Dumbbell Curl", "intermediate", "dumbbell", 3, "10-12", "Full stretch at bottom.",
    ["Bench at 60°, recline", "Arms hang at sides", "Curl DBs without moving elbows", "Lower fully"],
    ["Bringing elbows forward", "Cheating with body"],
    ["Allow full stretch", "Slow controlled curl"], []),
  Bi("Preacher Curl", "intermediate", "barbell", 3, "10-12", "Strict isolation.",
    ["Arms over preacher pad", "Curl bar to chin", "Squeeze top", "Lower until almost straight"],
    ["Locking out and bouncing", "Lifting elbows off pad"],
    ["Keep tension at bottom", "Slow eccentric"], []),
  Bi("Cable Curl", "beginner", "cable", 3, "12-15", "Constant tension.",
    ["Bar at low pulley", "Stand close, elbows at sides", "Curl up", "Resist on the way down"],
    ["Leaning back", "Elbows drifting forward"],
    ["Stay upright", "Squeeze at top"], []),
  Bi("Concentration Curl", "beginner", "dumbbell", 3, "10-12", "Pure isolation.",
    ["Seated, elbow on inner thigh", "Curl DB to shoulder", "Squeeze hard", "Lower fully"],
    ["Moving elbow", "Rounding back"],
    ["Brace elbow on thigh", "Pause 1 sec at top"], []),
  Bi("Spider Curl", "intermediate", "dumbbell", 3, "10-12", "Chest on incline, arms hang.",
    ["Lie face-down on incline bench", "DBs hang straight down", "Curl up, squeeze", "Lower fully"],
    ["Swinging", "Partial range"],
    ["Full stretch each rep", "Strict elbow position"], []),
  Bi("EZ Bar Curl", "beginner", "barbell", 3, "10-12", "Wrist-friendly grip.",
    ["EZ bar, inner grooves", "Curl to shoulders", "Squeeze top", "Lower fully"],
    ["Hyperextending wrists", "Cheating with hips"],
    ["Neutral wrist", "Elbows at sides"], ["Forearms"]),
  Bi("Reverse Curl", "intermediate", "barbell", 3, "10-12", "Overhand, forearms too.",
    ["Bar at thighs, palms down", "Curl to shoulders", "Squeeze", "Lower slow"],
    ["Going too heavy", "Wrist breaking"],
    ["Keep wrists straight", "Strict form"], ["Forearms"]),
  Bi("Zottman Curl", "intermediate", "dumbbell", 3, "10-12", "Curl up, reverse down.",
    ["Curl DBs up palms-up", "At top, rotate to palms-down", "Lower with reverse grip", "Rotate back at bottom"],
    ["Rushing the rotation"],
    ["Slow eccentric phase", "Smooth rotation"], ["Forearms"]),
  Bi("Bayesian Cable Curl", "advanced", "cable", 3, "10-12", "Behind body, full stretch.",
    ["Cable at low, face away", "Step forward, arm behind torso", "Curl up to face", "Lower with control"],
    ["Allowing shoulder to roll forward"],
    ["Keep elbow behind hip", "Squeeze hard at top"], []),
];

const triceps: Exercise[] = [
  Tr("Close-Grip Bench Press", "intermediate", "barbell", 4, "8-10", "Elbows tight to body.",
    ["Lie on bench, grip shoulder-width", "Lower to lower chest", "Press up, focus triceps", "Lock out"],
    ["Grip too narrow (wrist pain)", "Flaring elbows"],
    ["Shoulder-width grip ideal", "Tuck elbows in"], ["Chest","Front Delts"]),
  Tr("Tricep Dips", "intermediate", "bodyweight", 3, "8-12", "Stay upright for triceps.",
    ["Grip parallel bars", "Stay vertical, lower body", "Stop at 90° elbow", "Press up"],
    ["Leaning forward (chest focus)", "Going too deep"],
    ["Chest up", "Control descent"], ["Chest"]),
  Tr("Bench Dips", "beginner", "bodyweight", 3, "10-15", "Hands on bench behind you.",
    ["Hands on bench, feet on floor", "Lower hips toward floor", "Stop at 90°", "Press up"],
    ["Shrugging shoulders", "Going too low"],
    ["Keep shoulders down", "Elbows track straight back"], []),
  Tr("Overhead Tricep Extension", "beginner", "dumbbell", 3, "10-12", "Elbows point up.",
    ["DB held overhead with both hands", "Lower behind head", "Press back to top", "Keep elbows narrow"],
    ["Elbows flaring out wide", "Arching back"],
    ["Brace core", "Slow eccentric"], []),
  Tr("Skull Crushers", "intermediate", "barbell", 3, "8-12", "Lower to forehead, elbows fixed.",
    ["Lie on bench, EZ bar overhead", "Lower bar to forehead", "Elbows still", "Extend back up"],
    ["Letting elbows flare", "Locking out hard each rep"],
    ["Elbows point at ceiling", "Smooth controlled motion"], []),
  Tr("Tricep Pushdown", "beginner", "cable", 3, "10-15", "Elbows pinned, straight bar or rope.",
    ["Stand at high pulley", "Elbows at sides", "Push down to lockout", "Slow return"],
    ["Leaning forward", "Elbows drifting"],
    ["Brace abs", "Squeeze at bottom"], []),
  Tr("Rope Pushdown", "beginner", "cable", 3, "10-15", "Split rope at bottom.",
    ["Rope at high pulley", "Elbows at sides", "Push down, split rope ends", "Squeeze, slow return"],
    ["Using shoulders", "Locking elbows"],
    ["Pinky out at bottom", "Slow eccentric"], []),
  Tr("Diamond Push-Up", "intermediate", "bodyweight", 3, "8-12", "Hands form diamond.",
    ["Thumbs/index fingers touch", "Plank position", "Lower chest to hands", "Press up"],
    ["Flaring elbows", "Hips sagging"],
    ["Tuck elbows close", "Full plank"], ["Chest"]),
  Tr("Cable Overhead Extension", "intermediate", "cable", 3, "10-15", "Rope from low pulley.",
    ["Face away from low pulley, rope overhead", "Lower behind head", "Press back up", "Control"],
    ["Elbows flaring", "Body leaning back"],
    ["Stable elbows", "Brace core"], []),
  Tr("Kickback", "beginner", "dumbbell", 3, "12-15", "Hinge, extend arm back.",
    ["Hinge at hips, DB in hand", "Upper arm parallel to floor", "Extend forearm back", "Squeeze, return"],
    ["Swinging weight", "Upper arm moving"],
    ["Pin upper arm", "Squeeze at lockout"], []),
  Tr("Single-Arm Pushdown", "intermediate", "cable", 3, "10-12", "Unilateral isolation.",
    ["High pulley, single handle", "Elbow at side", "Push down to lockout", "Slow return"],
    ["Twisting torso", "Letting elbow drift"],
    ["Square shoulders", "Strict elbow position"], []),
  Tr("Tate Press", "advanced", "dumbbell", 3, "10-12", "DB to chest with bent elbows.",
    ["Lie on bench, DBs over chest, palms forward", "Lower DBs to chest with bent elbows", "Press up by extending elbows out", "Control"],
    ["Flaring elbows too wide", "Using too heavy"],
    ["Move only at elbow", "Light weight first"], []),
];

const forearms: Exercise[] = [
  Fa("Wrist Curl", "beginner", "dumbbell", 3, "12-15", "Forearms on knees, curl up.",
    ["Seat, forearms on thighs, palms up", "DB in hands, let wrist drop", "Curl wrist up", "Lower slow"],
    ["Moving elbows", "Going too heavy"],
    ["Isolate the wrist", "Full ROM"], []),
  Fa("Reverse Wrist Curl", "beginner", "dumbbell", 3, "12-15", "Palms down, extensor work.",
    ["Forearms on thighs, palms down", "DB in hands, wrist drops", "Curl wrist up", "Lower slow"],
    ["Using small range", "Too heavy"],
    ["Full extension and flexion", "Light is fine"], []),
  Fa("Farmer's Carry", "beginner", "dumbbell", 3, "30-60s", "Walk with heavy DBs.",
    ["Heavy DBs in each hand", "Stand tall, shoulders back", "Walk smoothly", "Set down with control"],
    ["Shrugging shoulders up", "Bending forward"],
    ["Pack shoulders down", "Tight core"], ["Traps","Core"]),
  Fa("Plate Pinch", "beginner", "bodyweight", 3, "20-40s", "Pinch plates, hold.",
    ["Stack 2 plates smooth-side out", "Pinch with fingers", "Stand and hold", "Drop safely"],
    ["Letting fingers slide"],
    ["Squeeze hard", "Breathe"], []),
  Fa("Dead Hang", "beginner", "bodyweight", 3, "20-45s", "Hang from bar.",
    ["Jump to bar, grip overhand", "Hang fully with active shoulders", "Hold time", "Drop safely"],
    ["Passive shoulder slump"],
    ["Pack shoulders", "Breathe and relax"], ["Lats"]),
  Fa("Wrist Roller", "intermediate", "bodyweight", 3, "2 reps", "Roll weight up and down.",
    ["Hold roller out in front", "Roll wrist over wrist to wind cord", "Then unwind", "Repeat"],
    ["Dropping arms"],
    ["Keep arms parallel to floor", "Slow controlled rolls"], []),
  Fa("Reverse Curl", "intermediate", "barbell", 3, "10-12", "Overhand, forearms too.",
    ["Bar at thighs palms down", "Curl to shoulders", "Squeeze", "Lower slow"],
    ["Wrist breaking", "Using momentum"],
    ["Neutral wrist", "Elbows at sides"], ["Biceps"]),
  Fa("Hammer Curl", "beginner", "dumbbell", 3, "10-12", "Neutral grip, big hitter.",
    ["DBs at sides, palms in", "Curl up with neutral grip", "Squeeze", "Lower"],
    ["Swinging"],
    ["Elbows fixed", "Pause at top"], ["Biceps"]),
  Fa("Towel Pull-Up", "advanced", "bodyweight", 3, "AMRAP", "Grip towel, brutal forearms.",
    ["Drape towel over bar", "Grip both ends", "Pull up to chin", "Lower slow"],
    ["Kipping", "Going too long sets without grip ready"],
    ["Tight crushing grip", "Build up reps slowly"], ["Back","Biceps"]),
  Fa("Behind-the-Back Wrist Curl", "intermediate", "barbell", 3, "12-15", "Bar behind back, sneaky pump.",
    ["Hold bar behind back, palms back", "Curl bar up using only wrists", "Squeeze", "Lower slow"],
    ["Using arms", "Hyperextending wrists"],
    ["Isolate wrist movement", "Light weight"], []),
];

const legs: Exercise[] = [
  L("Squat", "intermediate", "barbell", 4, "5-8", "Knees track over toes, chest up.",
    ["Bar on upper back, feet shoulder-width", "Brace core, sit back and down", "Hit at least parallel", "Drive through mid-foot up"],
    ["Knees caving in", "Heels lifting", "Rounding lower back"],
    ["Push knees out", "Stack ribs over hips", "Drive heels into floor"], ["Glutes","Core"]),
  L("Front Squat", "advanced", "barbell", 4, "5-8", "Bar on front rack, vertical torso.",
    ["Bar on front delts, elbows high", "Brace, descend with chest up", "Hit parallel or below", "Drive up"],
    ["Elbows dropping (losing bar)", "Knees caving"],
    ["Elbows high through full lift", "Push knees out"], ["Quads","Core"]),
  L("Goblet Squat", "beginner", "dumbbell", 3, "10-12", "DB at chest, beginner-friendly.",
    ["Hold DB vertically at chest", "Feet shoulder-width", "Squat down between knees", "Drive up"],
    ["Letting elbows dip and rounding back"],
    ["Elbows inside knees", "Chest tall"], ["Glutes"]),
  L("Bulgarian Split Squat", "intermediate", "dumbbell", 3, "8-10/leg", "Rear foot on bench.",
    ["Rear foot on bench, front foot far", "Lower back knee toward floor", "Drive through front heel", "Stand tall"],
    ["Front knee caving", "Leaning forward too much"],
    ["Most weight on front foot", "Front knee tracks over toes"], ["Glutes","Hamstrings"]),
  L("Walking Lunges", "beginner", "dumbbell", 3, "10/leg", "Push through heel.",
    ["Step forward into lunge", "Back knee near floor", "Drive front heel and step forward", "Alternate"],
    ["Short steps (knee over toe)", "Body lurching"],
    ["Front knee 90°, back knee 90°", "Long stride"], ["Glutes"]),
  L("Romanian Deadlift", "intermediate", "barbell", 4, "8-10", "Hinge at hips, soft knees.",
    ["Bar at thighs, soft knees", "Hinge hips back, lower bar", "Stop at mid-shin or end of stretch", "Stand tall"],
    ["Squatting instead of hinging", "Rounding back"],
    ["Push hips back, not down", "Bar slides down legs"], ["Glutes","Hamstrings","Back"]),
  L("Leg Press", "beginner", "machine", 3, "10-15", "Quad/glute builder.",
    ["Sit in leg press, feet shoulder-width", "Lower until knees ~90°", "Press up without locking", "Control descent"],
    ["Locking knees hard", "Lifting hips off pad"],
    ["Stop just before lockout", "Pin hips to seat"], ["Glutes"]),
  L("Leg Extension", "beginner", "machine", 3, "12-15", "Quad isolation.",
    ["Adjust pad above ankles", "Extend legs to lockout", "Squeeze 1 sec", "Lower slow"],
    ["Slamming weight", "Hyperextending"],
    ["Slow controlled reps", "Pause at top"], []),
  L("Lying Leg Curl", "beginner", "machine", 3, "10-15", "Hamstring isolation.",
    ["Lie face down, pad behind ankles", "Curl heels to glutes", "Squeeze", "Lower with control"],
    ["Lifting hips", "Using momentum"],
    ["Hips flat on pad", "Slow eccentric"], ["Hamstrings"]),
  L("Hack Squat", "intermediate", "machine", 3, "8-12", "Machine squat, quad focus.",
    ["Shoulders under pads, feet mid-platform", "Lower to parallel", "Drive up", "Don't lock"],
    ["Knees collapsing", "Half reps"],
    ["Push knees out", "Full ROM"], ["Glutes"]),
  L("Box Squat", "intermediate", "barbell", 3, "5-8", "Sit to box, then stand.",
    ["Stand in front of box, bar on back", "Sit back and down to box", "Pause briefly", "Drive up"],
    ["Crashing onto box"],
    ["Sit back, not down", "Stay tight on box"], ["Glutes","Core"]),
  L("Step-Ups", "beginner", "dumbbell", 3, "10/leg", "Step onto box, drive through heel.",
    ["DBs at sides", "Step up onto box with one foot", "Drive through heel", "Step down with control"],
    ["Pushing off back foot"],
    ["Use front leg only", "Box at knee height"], ["Glutes"]),
  L("Sissy Squat", "advanced", "bodyweight", 3, "8-12", "Lean back on toes — quads.",
    ["Hold support, rise on toes", "Lean back, drop knees forward", "Lower until upper body parallels floor", "Return"],
    ["Knee pain — stop"],
    ["Build up slowly", "Use support hand"], []),
];

const glutes: Exercise[] = [
  G("Hip Thrust", "intermediate", "barbell", 4, "8-12", "Upper back on bench, drive hips.",
    ["Shoulders on bench, bar over hips", "Plant feet shoulder-width", "Drive hips up to lockout", "Lower with control"],
    ["Hyperextending lower back", "Short ROM"],
    ["Tuck chin and ribs", "Squeeze glutes hard at top"], ["Hamstrings"]),
  G("Glute Bridge", "beginner", "bodyweight", 3, "12-15", "Bodyweight, learn the pattern.",
    ["Lie on back, knees bent", "Drive hips up", "Squeeze glutes", "Lower"],
    ["Pushing through toes"],
    ["Heels driven into floor", "Pause at top"], ["Hamstrings"]),
  G("Romanian Deadlift", "intermediate", "barbell", 4, "8-10", "Hinge, glutes/hams stretch.",
    ["Soft knees, bar at thighs", "Hinge hips back, lower bar", "Feel stretch in hams/glutes", "Stand tall"],
    ["Rounding back", "Squatting motion"],
    ["Push hips back", "Bar close to legs"], ["Hamstrings","Back"]),
  G("Cable Pull-Through", "beginner", "cable", 3, "12-15", "Rope between legs, hinge.",
    ["Face away from low pulley, rope between legs", "Hinge at hips", "Drive hips forward", "Squeeze glutes"],
    ["Squatting instead of hinging"],
    ["Push hips back, then thrust", "Soft knees"], ["Hamstrings"]),
  G("Reverse Lunge", "beginner", "dumbbell", 3, "10/leg", "Step back, glute focus.",
    ["DBs at sides", "Step one foot back", "Lower back knee", "Drive through front heel"],
    ["Short steps"],
    ["Long stride for glute stretch", "Push through front heel"], ["Quads"]),
  G("Curtsy Lunge", "intermediate", "dumbbell", 3, "10/leg", "Cross-step for glute med.",
    ["DBs at sides", "Step back foot behind and across", "Lower into lunge", "Drive up"],
    ["Knee caving"],
    ["Keep front knee tracking", "Squeeze glutes up"], ["Glute Medius"]),
  G("Single-Leg Glute Bridge", "beginner", "bodyweight", 3, "10/leg", "One leg in air.",
    ["Lie on back, one knee bent, other leg up", "Drive hip up with planted leg", "Squeeze glute", "Lower"],
    ["Hips tilting"],
    ["Square hips throughout", "Top pause"], ["Hamstrings"]),
  G("Donkey Kick", "beginner", "bodyweight", 3, "12/leg", "Kick heel to ceiling.",
    ["On all fours", "Lift one leg, knee bent", "Press heel to ceiling", "Lower with control"],
    ["Arching lower back"],
    ["Squeeze glute", "Move from hip, not lower back"], []),
  G("Frog Pump", "beginner", "bodyweight", 3, "15-20", "Heels together, knees out.",
    ["Lie on back, heels together, knees apart", "Drive hips up", "Squeeze glutes", "Lower"],
    ["Using lower back"],
    ["Push through outer heels", "Top squeeze"], []),
  G("Sumo Deadlift", "advanced", "barbell", 3, "5-8", "Wide stance, glute heavy.",
    ["Wide stance, toes out", "Grip bar inside knees", "Drive knees out, stand", "Lower with hips back"],
    ["Letting hips shoot up first"],
    ["Hips and shoulders rise together", "Knees track over toes"], ["Quads","Back"]),
  G("Kettlebell Swing", "intermediate", "kettlebell", 3, "15-20", "Hinge and snap.",
    ["KB between feet, hinge to grip", "Swing back between legs", "Snap hips to chest height", "Let it fall"],
    ["Squatting the swing", "Lifting with arms"],
    ["Power from hips", "Arms are ropes"], ["Hamstrings","Core"]),
  G("Banded Side Step", "beginner", "bands", 3, "12/side", "Band above knees.",
    ["Band above knees, half squat", "Step sideways", "Keep tension", "Reverse"],
    ["Standing fully up"],
    ["Stay low in half squat", "Push knees out"], ["Glute Medius"]),
];

const calves: Exercise[] = [
  Ca("Standing Calf Raise", "beginner", "bodyweight", 4, "12-20", "Full stretch, full squeeze.",
    ["Stand on edge of step", "Heels hang off", "Rise onto toes", "Lower past start"],
    ["Half reps"],
    ["Full ROM", "Pause at top"], []),
  Ca("Seated Calf Raise", "beginner", "machine", 4, "12-20", "Targets soleus.",
    ["Sit, knees under pad", "Drop heels below platform", "Press up onto toes", "Lower slow"],
    ["Bouncing"],
    ["Slow eccentric", "Squeeze 1 sec at top"], []),
  Ca("Single-Leg Calf Raise", "beginner", "bodyweight", 3, "12-15/leg", "Unilateral work.",
    ["One foot on step", "Other leg behind", "Rise onto toes", "Lower past start"],
    ["Cheating with other leg"],
    ["Slow controlled reps", "Hold support lightly"], []),
  Ca("Donkey Calf Raise", "intermediate", "bodyweight", 3, "15-20", "Hinged calf raise.",
    ["Hinge over bench, support upper body", "Toes on platform", "Rise onto toes", "Lower fully"],
    ["Partial range"],
    ["Stretch the bottom", "Squeeze the top"], []),
  Ca("Smith Machine Calf Raise", "beginner", "machine", 4, "12-15", "Stable load.",
    ["Bar on shoulders, toes on plate", "Rise high onto toes", "Pause", "Lower past start"],
    ["Bending knees"],
    ["Knees soft but locked", "Slow eccentric"], []),
  Ca("Box Jump", "intermediate", "bodyweight", 3, "5-8", "Explosive calves.",
    ["Stand in front of box", "Hinge slightly, swing arms", "Jump up and land soft", "Step down"],
    ["Jumping down (knees take impact)"],
    ["Step down, jump up", "Land soft on balls of feet"], ["Quads"]),
  Ca("Jump Rope", "beginner", "bodyweight", 3, "60s", "Skipping conditioning.",
    ["Rope at hip height", "Hop on balls of feet", "Wrist rotation, not arms", "Soft knees"],
    ["Jumping too high"],
    ["Small hops, fast cadence", "Stay light"], []),
  Ca("Farmer Walk on Toes", "intermediate", "dumbbell", 3, "30s", "Tip-toe walk.",
    ["Heavy DBs in hands", "Rise on toes", "Walk small steps", "Lower with control"],
    ["Dropping heels"],
    ["Stay tall on toes", "Tight core"], ["Forearms","Core"]),
];

const abs: Exercise[] = [
  A("Plank", "beginner", "bodyweight", 3, "30-60s", "Straight line head to heel.",
    ["Forearms on floor under shoulders", "Body straight", "Brace abs and glutes", "Hold"],
    ["Sagging hips", "Hips piking up"],
    ["Squeeze glutes", "Tuck pelvis slightly"], ["Core","Shoulders"]),
  A("Side Plank", "beginner", "bodyweight", 3, "30-45s/side", "Stack hips, brace.",
    ["Forearm under shoulder, body sideways", "Lift hips off floor", "Hold", "Switch sides"],
    ["Hips dropping"],
    ["Drive hips up", "Stack shoulders over elbow"], ["Obliques"]),
  A("Hanging Knee Raise", "intermediate", "bodyweight", 3, "10-15", "Curl knees to chest.",
    ["Hang from bar", "Bring knees to chest", "Don't swing", "Lower with control"],
    ["Using momentum"],
    ["Slow controlled raise", "Tuck pelvis at top"], []),
  A("Hanging Leg Raise", "advanced", "bodyweight", 3, "8-12", "Legs straight, brutal.",
    ["Hang from bar", "Raise straight legs to parallel or higher", "Lower slow", "No swinging"],
    ["Swinging body"],
    ["Brace lats and abs", "Posterior pelvic tilt"], []),
  A("Cable Crunch", "intermediate", "cable", 3, "10-15", "Kneel, crunch with rope.",
    ["Rope at high pulley", "Kneel, rope at forehead", "Crunch elbows to thighs", "Slow return"],
    ["Pulling with arms"],
    ["Curl spine, ribs to hips", "Don't hip-hinge"], []),
  A("Bicycle Crunches", "beginner", "bodyweight", 3, "20", "Slow, twist from core.",
    ["Lie on back, knees up", "Hands behind ears", "Twist elbow toward opposite knee", "Alternate"],
    ["Pulling on neck"],
    ["Slow controlled twists", "Elbows out"], ["Obliques"]),
  A("Russian Twist", "beginner", "dumbbell", 3, "20", "Side to side with DB.",
    ["Seated, lean back 45°, feet up", "Hold DB or plate", "Twist side to side", "Tap floor each side"],
    ["Rounding back"],
    ["Chest tall", "Twist from core"], ["Obliques"]),
  A("Dead Bug", "beginner", "bodyweight", 3, "10/side", "Opposite arm/leg.",
    ["Lie on back, arms up, knees 90°", "Lower opposite arm and leg", "Brace abs, don't arch", "Return, switch"],
    ["Lower back arching"],
    ["Press low back into floor", "Move slow"], ["Core"]),
  A("Mountain Climbers", "beginner", "bodyweight", 3, "30s", "Plank, drive knees.",
    ["Plank position", "Drive one knee to chest", "Quickly switch", "Repeat"],
    ["Hips bouncing high"],
    ["Stable plank", "Quick legs"], ["Core","Shoulders"]),
  A("V-Up", "intermediate", "bodyweight", 3, "10-15", "Touch toes in pike.",
    ["Lie flat, arms overhead", "Sit up and lift legs, touch toes", "Lower slow", "Repeat"],
    ["Using momentum, slamming"],
    ["Control both up and down", "Squeeze abs at top"], []),
  A("Ab Wheel Rollout", "advanced", "bodyweight", 3, "5-10", "Slow, controlled rollout.",
    ["Kneel with wheel under shoulders", "Roll out, body straight", "Stop before sagging", "Pull back in"],
    ["Sagging lower back at extension"],
    ["Brace 360°", "Tuck pelvis"], ["Core","Lats"]),
  A("Toes to Bar", "advanced", "bodyweight", 3, "5-10", "Strict hanging leg raise to bar.",
    ["Hang from bar", "Raise feet to bar", "Lower with control", "No kipping"],
    ["Kipping"],
    ["Strict only", "Build with knee raises first"], []),
];

const core: Exercise[] = [
  Co("Bird Dog", "beginner", "bodyweight", 3, "10/side", "Opposite arm/leg from quadruped.",
    ["On hands and knees", "Extend opposite arm and leg", "Hold 1 sec", "Return, switch"],
    ["Hips rotating"],
    ["Keep hips square", "Slow controlled motion"], []),
  Co("Pallof Press", "beginner", "cable", 3, "10/side", "Anti-rotation press.",
    ["Cable at chest height to side", "Hold at chest with two hands", "Press straight out", "Resist rotation"],
    ["Letting cable twist you"],
    ["Brace abs", "Slow and deliberate"], []),
  Co("Suitcase Carry", "beginner", "dumbbell", 3, "30s/side", "Heavy DB in one hand.",
    ["Heavy DB in one hand", "Stand tall, shoulders level", "Walk smoothly", "Switch sides"],
    ["Leaning to opposite side"],
    ["Stay tall and level", "Brace obliques"], ["Forearms"]),
  Co("Hollow Body Hold", "intermediate", "bodyweight", 3, "20-40s", "Banana hold.",
    ["Lie on back, arms overhead, legs out", "Lift shoulders and legs", "Low back pressed to floor", "Hold"],
    ["Low back arching"],
    ["Press low back down", "Brace abs hard"], ["Abs"]),
  Co("Farmer's Carry", "beginner", "dumbbell", 3, "30-60s", "Total body brace.",
    ["DBs in each hand", "Stand tall", "Walk straight", "Set down"],
    ["Bending forward"],
    ["Shoulders packed", "Tall posture"], ["Forearms","Traps"]),
  Co("Bear Crawl", "beginner", "bodyweight", 3, "30s", "Knees hover, crawl.",
    ["On hands and knees, knees hover 1\"", "Crawl opposite hand/foot", "Hips low and square", "Slow"],
    ["Hips swinging"],
    ["Stay low and stable", "Slow controlled"], ["Shoulders"]),
  Co("Turkish Get-Up", "advanced", "kettlebell", 2, "5/side", "Lie down to stand with KB overhead.",
    ["Lie on back, KB pressed overhead in one hand", "Roll to elbow, then hand, lift hips", "Sweep leg back to lunge", "Stand up; reverse it"],
    ["Eyes off KB", "Rushing"],
    ["Eyes on KB throughout", "Move one step at a time"], ["Shoulders","Glutes"]),
  Co("Renegade Row", "intermediate", "dumbbell", 3, "8/side", "Plank + DB row.",
    ["Plank on DBs", "Row one DB to hip", "Keep hips square", "Alternate"],
    ["Hips rotating"],
    ["Wide feet for stability", "Brace abs"], ["Back","Shoulders"]),
  Co("Side Plank Reach-Through", "intermediate", "bodyweight", 3, "10/side", "Twist under armpit.",
    ["Side plank position", "Thread top arm under torso", "Untwist and reach to ceiling", "Repeat"],
    ["Hips dropping"],
    ["Stay tall in side plank", "Slow twist"], ["Obliques"]),
  Co("Wood Chop", "intermediate", "cable", 3, "10/side", "Diagonal chop, high to low.",
    ["Cable at high pulley", "Pull handle down and across body", "Rotate hips", "Return slow"],
    ["Using arms only"],
    ["Drive from core and hips", "Long lever arms"], ["Obliques"]),
];

const fullBody: Exercise[] = [
  FB("Burpee", "intermediate", "bodyweight", 3, "10-15", "Squat, plank, push-up, jump.",
    ["Squat down, hands on floor", "Jump feet back to plank, push-up", "Jump feet forward", "Stand and jump"],
    ["Sagging in push-up", "Sloppy landing"],
    ["Solid plank each rep", "Soft landing"], ["Chest","Legs","Core"]),
  FB("Kettlebell Swing", "intermediate", "kettlebell", 3, "15-20", "Hinge, snap hips.",
    ["KB between feet, hinge to grip", "Swing back between legs", "Snap hips to chest height", "Let it fall"],
    ["Squatting", "Lifting with arms"],
    ["Power from hips", "Arms are ropes"], ["Glutes","Back","Core"]),
  FB("Clean and Press", "advanced", "barbell", 4, "5", "Pull to shoulders, press overhead.",
    ["Hinge to bar, explosive pull", "Catch at shoulders in front rack", "Brace and press overhead", "Lower in stages"],
    ["Pressing without catching solidly", "Hyperextending back"],
    ["Hips drive the bar up", "Brace before pressing"], ["Legs","Shoulders","Back"]),
  FB("Thruster", "intermediate", "dumbbell", 3, "10-12", "Squat into overhead press.",
    ["DBs at shoulders", "Squat to parallel", "Drive up and press overhead", "Lower to shoulders"],
    ["Pressing before standing"],
    ["Use leg drive into press", "One smooth motion"], ["Legs","Shoulders"]),
  FB("Devil's Press", "advanced", "dumbbell", 3, "6-10", "Burpee + DB snatch.",
    ["DBs on floor, squat down", "Jump back to plank with DBs", "Push-up, jump up", "Snatch DBs overhead"],
    ["Loss of form when tired"],
    ["Slow down — quality reps", "Use moderate weight"], ["Chest","Legs","Shoulders"]),
  FB("Mountain Climbers", "beginner", "bodyweight", 3, "30-45s", "Plank, drive knees alternating.",
    ["Strong plank", "Drive knee to chest", "Switch quickly", "Maintain plank"],
    ["Hips bouncing"],
    ["Stable plank", "Quick legs"], ["Core","Shoulders"]),
  FB("Jump Squat", "intermediate", "bodyweight", 3, "8-12", "Squat, explode up.",
    ["Feet shoulder-width", "Squat to parallel", "Explode up off floor", "Land soft, sink into next rep"],
    ["Hard landings"],
    ["Land softly through balls of feet", "Knees track toes"], ["Legs","Glutes","Calves"]),
  FB("Power Clean", "advanced", "barbell", 4, "3-5", "Floor to front rack explosively.",
    ["Setup like deadlift", "Pull explosively, shrug, pull under", "Catch at shoulders in quarter squat", "Stand tall"],
    ["Pulling with arms early", "Soft catch"],
    ["Triple extend (ankles, knees, hips)", "Aggressive catch"], ["Legs","Back","Shoulders"]),
  FB("Snatch", "advanced", "barbell", 4, "3-5", "Floor to overhead in one motion.",
    ["Wide grip on bar", "Pull explosively, get under bar", "Catch overhead in squat", "Stand"],
    ["Pressing out catch"],
    ["Coach this one — technique heavy", "Start very light"], ["Legs","Back","Shoulders"]),
  FB("Wall Ball", "intermediate", "bodyweight", 3, "15-20", "Squat, throw ball to target.",
    ["Hold med ball at chest", "Squat to parallel", "Drive up and throw ball to target", "Catch and repeat"],
    ["Half squats"],
    ["Hit target consistently", "Smooth catch and squat"], ["Legs","Shoulders","Core"]),
];

export const EXERCISES: Record<MuscleGroup, Exercise[]> = {
  Chest: chest,
  Back: back,
  Shoulders: shoulders,
  Biceps: biceps,
  Triceps: triceps,
  Forearms: forearms,
  Legs: legs,
  Glutes: glutes,
  Calves: calves,
  Abs: abs,
  Core: core,
  "Full Body": fullBody,
};

export const ALL_EXERCISES: Exercise[] = MUSCLE_GROUPS.flatMap((m) => EXERCISES[m]);

export const TOTAL_EXERCISE_COUNT = ALL_EXERCISES.length;
