// Built-in food database: 100+ ingredients and 100+ popular dishes
// All ingredient macros are per 100 g (edible portion). Dishes are per typical serving.

export interface Ingredient {
  name: string;
  serving_g: number;       // typical serving size in grams
  per100: { kcal: number; p: number; c: number; f: number };
  tags?: string[];         // for search ("indian", "veg", "protein", etc)
}

export interface Dish {
  name: string;
  cuisine: "indian" | "global";
  serving_g: number;
  kcal: number;
  p: number;
  c: number;
  f: number;
  ingredients: { name: string; grams: number }[]; // references INGREDIENT names when possible
}

export const INGREDIENTS: Ingredient[] = [
  // Grains & starches
  { name: "White Rice (cooked)", serving_g: 150, per100: { kcal: 130, p: 2.7, c: 28, f: 0.3 }, tags: ["grain", "indian"] },
  { name: "Brown Rice (cooked)", serving_g: 150, per100: { kcal: 123, p: 2.7, c: 26, f: 1 }, tags: ["grain"] },
  { name: "Basmati Rice (cooked)", serving_g: 150, per100: { kcal: 121, p: 3, c: 25, f: 0.4 }, tags: ["grain", "indian"] },
  { name: "Wheat Flour", serving_g: 30, per100: { kcal: 340, p: 12, c: 72, f: 1.5 }, tags: ["grain", "indian"] },
  { name: "Whole Wheat Chapati", serving_g: 40, per100: { kcal: 297, p: 11, c: 46, f: 7 }, tags: ["indian", "grain"] },
  { name: "Oats (cooked)", serving_g: 200, per100: { kcal: 71, p: 2.5, c: 12, f: 1.5 }, tags: ["grain"] },
  { name: "Quinoa (cooked)", serving_g: 150, per100: { kcal: 120, p: 4.4, c: 21, f: 1.9 }, tags: ["grain"] },
  { name: "Pasta (cooked)", serving_g: 150, per100: { kcal: 158, p: 5.8, c: 31, f: 0.9 }, tags: ["grain"] },
  { name: "Bread (white slice)", serving_g: 30, per100: { kcal: 265, p: 9, c: 49, f: 3.2 }, tags: ["grain"] },
  { name: "Bread (whole wheat slice)", serving_g: 30, per100: { kcal: 247, p: 13, c: 41, f: 3.4 }, tags: ["grain"] },
  { name: "Corn Tortilla", serving_g: 30, per100: { kcal: 218, p: 5.7, c: 45, f: 2.9 }, tags: ["grain"] },
  { name: "Flour Tortilla", serving_g: 40, per100: { kcal: 312, p: 8.2, c: 50, f: 8 }, tags: ["grain"] },
  { name: "Noodles (cooked)", serving_g: 150, per100: { kcal: 138, p: 4.5, c: 25, f: 2.1 }, tags: ["grain"] },
  { name: "Rice Noodles (cooked)", serving_g: 150, per100: { kcal: 109, p: 1.8, c: 25, f: 0.2 }, tags: ["grain"] },
  { name: "Couscous (cooked)", serving_g: 150, per100: { kcal: 112, p: 3.8, c: 23, f: 0.2 }, tags: ["grain"] },
  { name: "Polenta", serving_g: 150, per100: { kcal: 70, p: 1.5, c: 15, f: 0.3 }, tags: ["grain"] },
  { name: "Semolina (sooji)", serving_g: 30, per100: { kcal: 360, p: 12.7, c: 73, f: 1.1 }, tags: ["indian", "grain"] },
  { name: "Poha (flattened rice)", serving_g: 50, per100: { kcal: 346, p: 6.6, c: 77, f: 0.9 }, tags: ["indian", "grain"] },

  // Legumes & pulses
  { name: "Toor Dal (cooked)", serving_g: 150, per100: { kcal: 116, p: 8, c: 21, f: 0.5 }, tags: ["indian", "legume"] },
  { name: "Moong Dal (cooked)", serving_g: 150, per100: { kcal: 105, p: 7, c: 19, f: 0.4 }, tags: ["indian", "legume"] },
  { name: "Chana Dal (cooked)", serving_g: 150, per100: { kcal: 164, p: 8.9, c: 27, f: 2.6 }, tags: ["indian", "legume"] },
  { name: "Masoor Dal (cooked)", serving_g: 150, per100: { kcal: 116, p: 9, c: 20, f: 0.4 }, tags: ["indian", "legume"] },
  { name: "Chickpeas (cooked)", serving_g: 150, per100: { kcal: 164, p: 8.9, c: 27, f: 2.6 }, tags: ["legume", "indian"] },
  { name: "Kidney Beans (cooked)", serving_g: 150, per100: { kcal: 127, p: 8.7, c: 23, f: 0.5 }, tags: ["legume", "indian"] },
  { name: "Black Beans (cooked)", serving_g: 150, per100: { kcal: 132, p: 8.9, c: 24, f: 0.5 }, tags: ["legume"] },
  { name: "Lentils (cooked)", serving_g: 150, per100: { kcal: 116, p: 9, c: 20, f: 0.4 }, tags: ["legume"] },
  { name: "Soybeans (cooked)", serving_g: 100, per100: { kcal: 173, p: 17, c: 10, f: 9 }, tags: ["legume"] },
  { name: "Tofu", serving_g: 100, per100: { kcal: 76, p: 8, c: 1.9, f: 4.8 }, tags: ["legume", "veg"] },
  { name: "Tempeh", serving_g: 100, per100: { kcal: 192, p: 20, c: 7.6, f: 11 }, tags: ["legume"] },

  // Dairy & eggs
  { name: "Whole Milk", serving_g: 240, per100: { kcal: 61, p: 3.2, c: 4.8, f: 3.3 }, tags: ["dairy"] },
  { name: "Skim Milk", serving_g: 240, per100: { kcal: 34, p: 3.4, c: 5, f: 0.1 }, tags: ["dairy"] },
  { name: "Greek Yogurt", serving_g: 150, per100: { kcal: 59, p: 10, c: 3.6, f: 0.4 }, tags: ["dairy", "protein"] },
  { name: "Yogurt (curd)", serving_g: 150, per100: { kcal: 61, p: 3.5, c: 4.7, f: 3.3 }, tags: ["dairy", "indian"] },
  { name: "Paneer", serving_g: 50, per100: { kcal: 296, p: 18, c: 6, f: 22 }, tags: ["dairy", "indian", "protein"] },
  { name: "Cheddar Cheese", serving_g: 30, per100: { kcal: 403, p: 25, c: 1.3, f: 33 }, tags: ["dairy"] },
  { name: "Mozzarella Cheese", serving_g: 30, per100: { kcal: 280, p: 22, c: 2.2, f: 22 }, tags: ["dairy"] },
  { name: "Parmesan Cheese", serving_g: 20, per100: { kcal: 431, p: 38, c: 4.1, f: 29 }, tags: ["dairy"] },
  { name: "Cream Cheese", serving_g: 30, per100: { kcal: 342, p: 6, c: 4.1, f: 34 }, tags: ["dairy"] },
  { name: "Heavy Cream", serving_g: 30, per100: { kcal: 340, p: 2.8, c: 2.8, f: 36 }, tags: ["dairy"] },
  { name: "Butter", serving_g: 10, per100: { kcal: 717, p: 0.9, c: 0.1, f: 81 }, tags: ["fat", "dairy"] },
  { name: "Ghee", serving_g: 10, per100: { kcal: 900, p: 0, c: 0, f: 100 }, tags: ["fat", "indian"] },
  { name: "Egg (whole)", serving_g: 50, per100: { kcal: 155, p: 13, c: 1.1, f: 11 }, tags: ["protein"] },
  { name: "Egg White", serving_g: 33, per100: { kcal: 52, p: 11, c: 0.7, f: 0.2 }, tags: ["protein"] },

  // Meat & seafood
  { name: "Chicken Breast (cooked)", serving_g: 120, per100: { kcal: 165, p: 31, c: 0, f: 3.6 }, tags: ["protein", "meat"] },
  { name: "Chicken Thigh (cooked)", serving_g: 120, per100: { kcal: 209, p: 26, c: 0, f: 11 }, tags: ["protein", "meat"] },
  { name: "Ground Chicken (cooked)", serving_g: 120, per100: { kcal: 189, p: 24, c: 0, f: 10 }, tags: ["protein", "meat"] },
  { name: "Beef (lean, cooked)", serving_g: 120, per100: { kcal: 250, p: 26, c: 0, f: 15 }, tags: ["protein", "meat"] },
  { name: "Ground Beef (cooked)", serving_g: 120, per100: { kcal: 254, p: 26, c: 0, f: 17 }, tags: ["protein", "meat"] },
  { name: "Pork (cooked)", serving_g: 120, per100: { kcal: 242, p: 27, c: 0, f: 14 }, tags: ["protein", "meat"] },
  { name: "Bacon", serving_g: 20, per100: { kcal: 541, p: 37, c: 1.4, f: 42 }, tags: ["protein", "meat"] },
  { name: "Lamb (cooked)", serving_g: 120, per100: { kcal: 294, p: 25, c: 0, f: 21 }, tags: ["protein", "meat"] },
  { name: "Salmon (cooked)", serving_g: 120, per100: { kcal: 208, p: 20, c: 0, f: 13 }, tags: ["protein", "fish"] },
  { name: "Tuna (canned in water)", serving_g: 100, per100: { kcal: 116, p: 26, c: 0, f: 0.8 }, tags: ["protein", "fish"] },
  { name: "Tilapia (cooked)", serving_g: 120, per100: { kcal: 128, p: 26, c: 0, f: 2.7 }, tags: ["protein", "fish"] },
  { name: "Cod (cooked)", serving_g: 120, per100: { kcal: 105, p: 23, c: 0, f: 0.9 }, tags: ["protein", "fish"] },
  { name: "Shrimp (cooked)", serving_g: 100, per100: { kcal: 99, p: 24, c: 0.2, f: 0.3 }, tags: ["protein", "fish"] },
  { name: "Fish (white, cooked)", serving_g: 120, per100: { kcal: 130, p: 23, c: 0, f: 4 }, tags: ["protein", "fish", "indian"] },

  // Vegetables
  { name: "Potato (boiled)", serving_g: 150, per100: { kcal: 87, p: 1.9, c: 20, f: 0.1 }, tags: ["veg"] },
  { name: "Sweet Potato (cooked)", serving_g: 150, per100: { kcal: 90, p: 2, c: 21, f: 0.2 }, tags: ["veg"] },
  { name: "Tomato", serving_g: 100, per100: { kcal: 18, p: 0.9, c: 3.9, f: 0.2 }, tags: ["veg", "indian"] },
  { name: "Onion", serving_g: 80, per100: { kcal: 40, p: 1.1, c: 9.3, f: 0.1 }, tags: ["veg", "indian"] },
  { name: "Garlic", serving_g: 5, per100: { kcal: 149, p: 6.4, c: 33, f: 0.5 }, tags: ["veg", "indian"] },
  { name: "Ginger", serving_g: 5, per100: { kcal: 80, p: 1.8, c: 18, f: 0.8 }, tags: ["veg", "indian"] },
  { name: "Spinach", serving_g: 100, per100: { kcal: 23, p: 2.9, c: 3.6, f: 0.4 }, tags: ["veg", "indian"] },
  { name: "Broccoli", serving_g: 100, per100: { kcal: 34, p: 2.8, c: 7, f: 0.4 }, tags: ["veg"] },
  { name: "Cauliflower", serving_g: 100, per100: { kcal: 25, p: 1.9, c: 5, f: 0.3 }, tags: ["veg", "indian"] },
  { name: "Carrots", serving_g: 100, per100: { kcal: 41, p: 0.9, c: 10, f: 0.2 }, tags: ["veg"] },
  { name: "Peas (cooked)", serving_g: 100, per100: { kcal: 84, p: 5.4, c: 16, f: 0.4 }, tags: ["veg", "indian"] },
  { name: "Bell Pepper", serving_g: 100, per100: { kcal: 31, p: 1, c: 6, f: 0.3 }, tags: ["veg"] },
  { name: "Cabbage", serving_g: 100, per100: { kcal: 25, p: 1.3, c: 5.8, f: 0.1 }, tags: ["veg"] },
  { name: "Cucumber", serving_g: 100, per100: { kcal: 16, p: 0.7, c: 3.6, f: 0.1 }, tags: ["veg"] },
  { name: "Lettuce", serving_g: 50, per100: { kcal: 15, p: 1.4, c: 2.9, f: 0.2 }, tags: ["veg"] },
  { name: "Mushrooms", serving_g: 100, per100: { kcal: 22, p: 3.1, c: 3.3, f: 0.3 }, tags: ["veg"] },
  { name: "Eggplant", serving_g: 100, per100: { kcal: 25, p: 1, c: 6, f: 0.2 }, tags: ["veg", "indian"] },
  { name: "Okra (bhindi)", serving_g: 100, per100: { kcal: 33, p: 1.9, c: 7.5, f: 0.2 }, tags: ["veg", "indian"] },
  { name: "Bottle Gourd (lauki)", serving_g: 100, per100: { kcal: 14, p: 0.6, c: 3.4, f: 0.02 }, tags: ["veg", "indian"] },
  { name: "Bitter Gourd (karela)", serving_g: 100, per100: { kcal: 17, p: 1, c: 3.7, f: 0.2 }, tags: ["veg", "indian"] },
  { name: "Zucchini", serving_g: 100, per100: { kcal: 17, p: 1.2, c: 3.1, f: 0.3 }, tags: ["veg"] },
  { name: "Avocado", serving_g: 100, per100: { kcal: 160, p: 2, c: 9, f: 15 }, tags: ["veg", "fat"] },
  { name: "Corn (cooked)", serving_g: 100, per100: { kcal: 96, p: 3.4, c: 21, f: 1.5 }, tags: ["veg"] },

  // Fruits
  { name: "Apple", serving_g: 150, per100: { kcal: 52, p: 0.3, c: 14, f: 0.2 }, tags: ["fruit"] },
  { name: "Banana", serving_g: 120, per100: { kcal: 89, p: 1.1, c: 23, f: 0.3 }, tags: ["fruit"] },
  { name: "Orange", serving_g: 130, per100: { kcal: 47, p: 0.9, c: 12, f: 0.1 }, tags: ["fruit"] },
  { name: "Mango", serving_g: 150, per100: { kcal: 60, p: 0.8, c: 15, f: 0.4 }, tags: ["fruit", "indian"] },
  { name: "Strawberries", serving_g: 100, per100: { kcal: 32, p: 0.7, c: 7.7, f: 0.3 }, tags: ["fruit"] },
  { name: "Blueberries", serving_g: 100, per100: { kcal: 57, p: 0.7, c: 14, f: 0.3 }, tags: ["fruit"] },
  { name: "Grapes", serving_g: 100, per100: { kcal: 69, p: 0.7, c: 18, f: 0.2 }, tags: ["fruit"] },
  { name: "Pineapple", serving_g: 100, per100: { kcal: 50, p: 0.5, c: 13, f: 0.1 }, tags: ["fruit"] },
  { name: "Watermelon", serving_g: 200, per100: { kcal: 30, p: 0.6, c: 7.6, f: 0.2 }, tags: ["fruit"] },

  // Fats & oils
  { name: "Olive Oil", serving_g: 10, per100: { kcal: 884, p: 0, c: 0, f: 100 }, tags: ["fat"] },
  { name: "Mustard Oil", serving_g: 10, per100: { kcal: 884, p: 0, c: 0, f: 100 }, tags: ["fat", "indian"] },
  { name: "Coconut Oil", serving_g: 10, per100: { kcal: 862, p: 0, c: 0, f: 100 }, tags: ["fat"] },
  { name: "Sunflower Oil", serving_g: 10, per100: { kcal: 884, p: 0, c: 0, f: 100 }, tags: ["fat"] },
  { name: "Vegetable Oil", serving_g: 10, per100: { kcal: 884, p: 0, c: 0, f: 100 }, tags: ["fat"] },
  { name: "Peanut Butter", serving_g: 30, per100: { kcal: 588, p: 25, c: 20, f: 50 }, tags: ["fat", "protein"] },
  { name: "Almonds", serving_g: 28, per100: { kcal: 579, p: 21, c: 22, f: 50 }, tags: ["fat", "nut"] },
  { name: "Cashews", serving_g: 28, per100: { kcal: 553, p: 18, c: 30, f: 44 }, tags: ["fat", "nut", "indian"] },
  { name: "Walnuts", serving_g: 28, per100: { kcal: 654, p: 15, c: 14, f: 65 }, tags: ["fat", "nut"] },
  { name: "Peanuts", serving_g: 28, per100: { kcal: 567, p: 26, c: 16, f: 49 }, tags: ["fat", "nut"] },
  { name: "Coconut (grated)", serving_g: 30, per100: { kcal: 354, p: 3.3, c: 15, f: 33 }, tags: ["fat", "indian"] },

  // Spices, sugars, condiments
  { name: "Sugar", serving_g: 5, per100: { kcal: 387, p: 0, c: 100, f: 0 }, tags: ["sweet"] },
  { name: "Honey", serving_g: 21, per100: { kcal: 304, p: 0.3, c: 82, f: 0 }, tags: ["sweet"] },
  { name: "Maple Syrup", serving_g: 20, per100: { kcal: 260, p: 0, c: 67, f: 0.2 }, tags: ["sweet"] },
  { name: "Salt", serving_g: 1, per100: { kcal: 0, p: 0, c: 0, f: 0 } },
  { name: "Turmeric", serving_g: 2, per100: { kcal: 354, p: 8, c: 65, f: 10 }, tags: ["spice", "indian"] },
  { name: "Cumin", serving_g: 2, per100: { kcal: 375, p: 18, c: 44, f: 22 }, tags: ["spice", "indian"] },
  { name: "Coriander Powder", serving_g: 2, per100: { kcal: 298, p: 12, c: 55, f: 17 }, tags: ["spice", "indian"] },
  { name: "Garam Masala", serving_g: 2, per100: { kcal: 379, p: 14, c: 50, f: 15 }, tags: ["spice", "indian"] },
  { name: "Chili Powder", serving_g: 2, per100: { kcal: 282, p: 13, c: 50, f: 14 }, tags: ["spice", "indian"] },
  { name: "Black Pepper", serving_g: 1, per100: { kcal: 251, p: 10, c: 64, f: 3.3 }, tags: ["spice"] },
  { name: "Soy Sauce", serving_g: 15, per100: { kcal: 53, p: 8, c: 4.9, f: 0.6 }, tags: ["sauce"] },
  { name: "Ketchup", serving_g: 15, per100: { kcal: 101, p: 1.7, c: 27, f: 0.1 }, tags: ["sauce"] },
  { name: "Mayonnaise", serving_g: 15, per100: { kcal: 680, p: 1, c: 0.6, f: 75 }, tags: ["sauce", "fat"] },
  { name: "Tomato Sauce", serving_g: 60, per100: { kcal: 29, p: 1.6, c: 6.4, f: 0.2 }, tags: ["sauce"] },
  { name: "Coconut Milk", serving_g: 60, per100: { kcal: 230, p: 2.3, c: 5.5, f: 24 }, tags: ["sauce", "indian"] },
];

function ing(name: string, grams: number) {
  return { name, grams };
}

// Helper to build dish macros from ingredient list when desired (used only at dev time)
// For built-ins below, the totals are precomputed and edited for realism.

export const DISHES: Dish[] = [
  // ============ INDIAN (40+) ============
  { name: "Butter Chicken", cuisine: "indian", serving_g: 300, kcal: 490, p: 32, c: 12, f: 35,
    ingredients: [ing("Chicken Thigh (cooked)", 180), ing("Tomato", 60), ing("Heavy Cream", 30), ing("Butter", 15), ing("Onion", 30), ing("Garam Masala", 2), ing("Ginger", 5)] },
  { name: "Dal Tadka", cuisine: "indian", serving_g: 250, kcal: 280, p: 14, c: 38, f: 8,
    ingredients: [ing("Toor Dal (cooked)", 200), ing("Ghee", 8), ing("Tomato", 30), ing("Onion", 30), ing("Cumin", 2), ing("Turmeric", 1)] },
  { name: "Rajma Chawal", cuisine: "indian", serving_g: 400, kcal: 540, p: 18, c: 92, f: 10,
    ingredients: [ing("Kidney Beans (cooked)", 150), ing("Basmati Rice (cooked)", 200), ing("Onion", 30), ing("Tomato", 40), ing("Garam Masala", 2)] },
  { name: "Chole Bhature", cuisine: "indian", serving_g: 350, kcal: 720, p: 18, c: 88, f: 32,
    ingredients: [ing("Chickpeas (cooked)", 150), ing("Wheat Flour", 100), ing("Vegetable Oil", 25), ing("Onion", 30), ing("Tomato", 30)] },
  { name: "Paneer Butter Masala", cuisine: "indian", serving_g: 300, kcal: 520, p: 22, c: 18, f: 38,
    ingredients: [ing("Paneer", 120), ing("Tomato", 80), ing("Heavy Cream", 40), ing("Butter", 15), ing("Cashews", 10)] },
  { name: "Palak Paneer", cuisine: "indian", serving_g: 300, kcal: 380, p: 22, c: 12, f: 26,
    ingredients: [ing("Paneer", 100), ing("Spinach", 200), ing("Heavy Cream", 20), ing("Ghee", 10), ing("Garlic", 5)] },
  { name: "Chicken Biryani", cuisine: "indian", serving_g: 400, kcal: 620, p: 32, c: 70, f: 22,
    ingredients: [ing("Basmati Rice (cooked)", 220), ing("Chicken Thigh (cooked)", 150), ing("Yogurt (curd)", 30), ing("Ghee", 12), ing("Onion", 30)] },
  { name: "Vegetable Biryani", cuisine: "indian", serving_g: 400, kcal: 520, p: 12, c: 82, f: 16,
    ingredients: [ing("Basmati Rice (cooked)", 250), ing("Peas (cooked)", 40), ing("Carrots", 40), ing("Ghee", 10), ing("Cashews", 10)] },
  { name: "Plain Dosa", cuisine: "indian", serving_g: 120, kcal: 230, p: 5, c: 38, f: 6,
    ingredients: [ing("White Rice (cooked)", 100), ing("Lentils (cooked)", 40), ing("Vegetable Oil", 5)] },
  { name: "Masala Dosa", cuisine: "indian", serving_g: 200, kcal: 380, p: 8, c: 60, f: 11,
    ingredients: [ing("White Rice (cooked)", 120), ing("Lentils (cooked)", 40), ing("Potato (boiled)", 80), ing("Vegetable Oil", 8)] },
  { name: "Idli (2 pieces)", cuisine: "indian", serving_g: 120, kcal: 158, p: 5, c: 33, f: 1,
    ingredients: [ing("White Rice (cooked)", 80), ing("Lentils (cooked)", 30)] },
  { name: "Poha", cuisine: "indian", serving_g: 180, kcal: 270, p: 6, c: 45, f: 7,
    ingredients: [ing("Poha (flattened rice)", 50), ing("Onion", 40), ing("Peanuts", 12), ing("Vegetable Oil", 6)] },
  { name: "Upma", cuisine: "indian", serving_g: 200, kcal: 290, p: 7, c: 48, f: 8,
    ingredients: [ing("Semolina (sooji)", 50), ing("Onion", 30), ing("Vegetable Oil", 8)] },
  { name: "Samosa (1 piece)", cuisine: "indian", serving_g: 80, kcal: 260, p: 4, c: 28, f: 14,
    ingredients: [ing("Wheat Flour", 30), ing("Potato (boiled)", 40), ing("Peas (cooked)", 10), ing("Vegetable Oil", 10)] },
  { name: "Aloo Paratha", cuisine: "indian", serving_g: 150, kcal: 330, p: 7, c: 48, f: 12,
    ingredients: [ing("Wheat Flour", 70), ing("Potato (boiled)", 60), ing("Ghee", 10)] },
  { name: "Plain Paratha", cuisine: "indian", serving_g: 80, kcal: 260, p: 6, c: 38, f: 9,
    ingredients: [ing("Wheat Flour", 60), ing("Ghee", 8)] },
  { name: "Pav Bhaji", cuisine: "indian", serving_g: 350, kcal: 560, p: 12, c: 78, f: 22,
    ingredients: [ing("Bread (white slice)", 100), ing("Potato (boiled)", 100), ing("Peas (cooked)", 40), ing("Butter", 20), ing("Tomato", 60)] },
  { name: "Aloo Gobi", cuisine: "indian", serving_g: 250, kcal: 220, p: 6, c: 30, f: 9,
    ingredients: [ing("Potato (boiled)", 120), ing("Cauliflower", 120), ing("Vegetable Oil", 8)] },
  { name: "Kadai Paneer", cuisine: "indian", serving_g: 280, kcal: 430, p: 20, c: 18, f: 30,
    ingredients: [ing("Paneer", 120), ing("Bell Pepper", 80), ing("Tomato", 60), ing("Vegetable Oil", 12)] },
  { name: "Chicken Curry", cuisine: "indian", serving_g: 300, kcal: 380, p: 30, c: 10, f: 24,
    ingredients: [ing("Chicken Thigh (cooked)", 180), ing("Onion", 40), ing("Tomato", 40), ing("Vegetable Oil", 12)] },
  { name: "Fish Curry", cuisine: "indian", serving_g: 280, kcal: 320, p: 26, c: 8, f: 20,
    ingredients: [ing("Fish (white, cooked)", 150), ing("Coconut Milk", 50), ing("Onion", 30), ing("Tomato", 30)] },
  { name: "Khichdi", cuisine: "indian", serving_g: 300, kcal: 330, p: 11, c: 55, f: 7,
    ingredients: [ing("White Rice (cooked)", 150), ing("Moong Dal (cooked)", 100), ing("Ghee", 8)] },
  { name: "Naan", cuisine: "indian", serving_g: 90, kcal: 270, p: 8, c: 45, f: 6,
    ingredients: [ing("Wheat Flour", 70), ing("Yogurt (curd)", 20), ing("Ghee", 6)] },
  { name: "Garlic Naan", cuisine: "indian", serving_g: 100, kcal: 310, p: 9, c: 48, f: 9,
    ingredients: [ing("Wheat Flour", 75), ing("Garlic", 5), ing("Butter", 8)] },
  { name: "Roti / Chapati", cuisine: "indian", serving_g: 40, kcal: 120, p: 4, c: 18, f: 3,
    ingredients: [ing("Whole Wheat Chapati", 40)] },
  { name: "Tandoori Chicken", cuisine: "indian", serving_g: 200, kcal: 290, p: 38, c: 4, f: 14,
    ingredients: [ing("Chicken Thigh (cooked)", 180), ing("Yogurt (curd)", 30), ing("Garam Masala", 2)] },
  { name: "Chicken Tikka", cuisine: "indian", serving_g: 180, kcal: 290, p: 36, c: 4, f: 14,
    ingredients: [ing("Chicken Breast (cooked)", 150), ing("Yogurt (curd)", 25), ing("Garam Masala", 2)] },
  { name: "Paneer Tikka", cuisine: "indian", serving_g: 180, kcal: 360, p: 20, c: 8, f: 28,
    ingredients: [ing("Paneer", 120), ing("Yogurt (curd)", 25), ing("Bell Pepper", 30)] },
  { name: "Vada Pav", cuisine: "indian", serving_g: 150, kcal: 290, p: 7, c: 40, f: 12,
    ingredients: [ing("Bread (white slice)", 60), ing("Potato (boiled)", 70), ing("Vegetable Oil", 8)] },
  { name: "Dhokla", cuisine: "indian", serving_g: 150, kcal: 220, p: 8, c: 36, f: 5,
    ingredients: [ing("Chana Dal (cooked)", 80), ing("Semolina (sooji)", 30)] },
  { name: "Bhindi Masala", cuisine: "indian", serving_g: 200, kcal: 180, p: 4, c: 18, f: 11,
    ingredients: [ing("Okra (bhindi)", 150), ing("Onion", 30), ing("Vegetable Oil", 10)] },
  { name: "Baingan Bharta", cuisine: "indian", serving_g: 220, kcal: 190, p: 4, c: 16, f: 12,
    ingredients: [ing("Eggplant", 180), ing("Onion", 30), ing("Tomato", 30), ing("Vegetable Oil", 10)] },
  { name: "Sambar", cuisine: "indian", serving_g: 250, kcal: 180, p: 9, c: 26, f: 5,
    ingredients: [ing("Toor Dal (cooked)", 120), ing("Carrots", 40), ing("Bottle Gourd (lauki)", 40), ing("Tamarind/Spice", 2)] },
  { name: "Rasam", cuisine: "indian", serving_g: 200, kcal: 90, p: 3, c: 14, f: 2,
    ingredients: [ing("Toor Dal (cooked)", 50), ing("Tomato", 60), ing("Cumin", 2)] },
  { name: "Pulao", cuisine: "indian", serving_g: 250, kcal: 340, p: 7, c: 56, f: 10,
    ingredients: [ing("Basmati Rice (cooked)", 180), ing("Peas (cooked)", 30), ing("Ghee", 8)] },
  { name: "Curd Rice", cuisine: "indian", serving_g: 250, kcal: 290, p: 9, c: 42, f: 9,
    ingredients: [ing("White Rice (cooked)", 150), ing("Yogurt (curd)", 80)] },
  { name: "Lassi (sweet)", cuisine: "indian", serving_g: 250, kcal: 220, p: 6, c: 32, f: 7,
    ingredients: [ing("Yogurt (curd)", 200), ing("Sugar", 20)] },
  { name: "Gulab Jamun (2 pieces)", cuisine: "indian", serving_g: 100, kcal: 340, p: 4, c: 50, f: 14,
    ingredients: [ing("Wheat Flour", 30), ing("Sugar", 35), ing("Ghee", 10)] },
  { name: "Jalebi", cuisine: "indian", serving_g: 100, kcal: 360, p: 2, c: 65, f: 11,
    ingredients: [ing("Wheat Flour", 35), ing("Sugar", 45), ing("Vegetable Oil", 12)] },
  { name: "Kheer", cuisine: "indian", serving_g: 200, kcal: 290, p: 7, c: 40, f: 11,
    ingredients: [ing("Whole Milk", 180), ing("White Rice (cooked)", 30), ing("Sugar", 18)] },
  { name: "Pani Puri (6 pieces)", cuisine: "indian", serving_g: 150, kcal: 240, p: 5, c: 38, f: 7,
    ingredients: [ing("Wheat Flour", 40), ing("Potato (boiled)", 50), ing("Chickpeas (cooked)", 30)] },
  { name: "Bhel Puri", cuisine: "indian", serving_g: 150, kcal: 280, p: 6, c: 44, f: 9,
    ingredients: [ing("Poha (flattened rice)", 30), ing("Onion", 30), ing("Potato (boiled)", 40), ing("Peanuts", 10)] },

  // ============ GLOBAL (60+) ============
  { name: "Margherita Pizza (slice)", cuisine: "global", serving_g: 120, kcal: 280, p: 12, c: 36, f: 10,
    ingredients: [ing("Wheat Flour", 60), ing("Mozzarella Cheese", 30), ing("Tomato Sauce", 30)] },
  { name: "Pepperoni Pizza (slice)", cuisine: "global", serving_g: 130, kcal: 330, p: 14, c: 36, f: 14,
    ingredients: [ing("Wheat Flour", 60), ing("Mozzarella Cheese", 30), ing("Bacon", 15), ing("Tomato Sauce", 25)] },
  { name: "Cheeseburger", cuisine: "global", serving_g: 220, kcal: 520, p: 28, c: 40, f: 28,
    ingredients: [ing("Bread (white slice)", 80), ing("Ground Beef (cooked)", 100), ing("Cheddar Cheese", 25), ing("Lettuce", 10)] },
  { name: "Hamburger", cuisine: "global", serving_g: 200, kcal: 450, p: 25, c: 40, f: 22,
    ingredients: [ing("Bread (white slice)", 80), ing("Ground Beef (cooked)", 100), ing("Lettuce", 10), ing("Tomato", 20)] },
  { name: "Chicken Burger", cuisine: "global", serving_g: 220, kcal: 470, p: 30, c: 42, f: 18,
    ingredients: [ing("Bread (white slice)", 80), ing("Chicken Breast (cooked)", 120), ing("Mayonnaise", 10)] },
  { name: "Spaghetti Bolognese", cuisine: "global", serving_g: 350, kcal: 560, p: 28, c: 70, f: 18,
    ingredients: [ing("Pasta (cooked)", 200), ing("Ground Beef (cooked)", 100), ing("Tomato Sauce", 80)] },
  { name: "Spaghetti Carbonara", cuisine: "global", serving_g: 320, kcal: 640, p: 24, c: 72, f: 28,
    ingredients: [ing("Pasta (cooked)", 200), ing("Bacon", 30), ing("Egg (whole)", 50), ing("Parmesan Cheese", 20)] },
  { name: "Penne Arrabbiata", cuisine: "global", serving_g: 320, kcal: 460, p: 12, c: 78, f: 11,
    ingredients: [ing("Pasta (cooked)", 220), ing("Tomato Sauce", 100), ing("Olive Oil", 12)] },
  { name: "Lasagna", cuisine: "global", serving_g: 350, kcal: 620, p: 30, c: 50, f: 30,
    ingredients: [ing("Pasta (cooked)", 150), ing("Ground Beef (cooked)", 120), ing("Mozzarella Cheese", 50), ing("Tomato Sauce", 80)] },
  { name: "Sushi (6 pieces)", cuisine: "global", serving_g: 200, kcal: 280, p: 9, c: 48, f: 4,
    ingredients: [ing("White Rice (cooked)", 130), ing("Salmon (cooked)", 50), ing("Avocado", 20)] },
  { name: "Salmon Nigiri (2)", cuisine: "global", serving_g: 60, kcal: 100, p: 6, c: 16, f: 1.5,
    ingredients: [ing("White Rice (cooked)", 40), ing("Salmon (cooked)", 20)] },
  { name: "California Roll (8 pieces)", cuisine: "global", serving_g: 250, kcal: 380, p: 9, c: 60, f: 11,
    ingredients: [ing("White Rice (cooked)", 150), ing("Avocado", 40), ing("Mayonnaise", 15)] },
  { name: "Chicken Ramen", cuisine: "global", serving_g: 500, kcal: 540, p: 28, c: 70, f: 16,
    ingredients: [ing("Noodles (cooked)", 220), ing("Chicken Thigh (cooked)", 100), ing("Egg (whole)", 50), ing("Soy Sauce", 15)] },
  { name: "Tonkotsu Ramen", cuisine: "global", serving_g: 500, kcal: 620, p: 26, c: 68, f: 24,
    ingredients: [ing("Noodles (cooked)", 220), ing("Pork (cooked)", 90), ing("Egg (whole)", 50)] },
  { name: "Beef Tacos (2)", cuisine: "global", serving_g: 220, kcal: 460, p: 22, c: 40, f: 22,
    ingredients: [ing("Corn Tortilla", 60), ing("Ground Beef (cooked)", 100), ing("Cheddar Cheese", 20), ing("Lettuce", 10)] },
  { name: "Chicken Tacos (2)", cuisine: "global", serving_g: 220, kcal: 420, p: 26, c: 40, f: 16,
    ingredients: [ing("Corn Tortilla", 60), ing("Chicken Breast (cooked)", 100), ing("Avocado", 20)] },
  { name: "Burrito", cuisine: "global", serving_g: 350, kcal: 640, p: 28, c: 70, f: 26,
    ingredients: [ing("Flour Tortilla", 100), ing("Ground Beef (cooked)", 100), ing("Black Beans (cooked)", 80), ing("White Rice (cooked)", 60)] },
  { name: "Chicken Burrito", cuisine: "global", serving_g: 350, kcal: 600, p: 32, c: 70, f: 18,
    ingredients: [ing("Flour Tortilla", 100), ing("Chicken Breast (cooked)", 100), ing("Black Beans (cooked)", 80), ing("White Rice (cooked)", 60)] },
  { name: "Quesadilla", cuisine: "global", serving_g: 200, kcal: 520, p: 22, c: 42, f: 28,
    ingredients: [ing("Flour Tortilla", 100), ing("Cheddar Cheese", 50), ing("Chicken Breast (cooked)", 50)] },
  { name: "Vegetable Fried Rice", cuisine: "global", serving_g: 300, kcal: 420, p: 10, c: 68, f: 12,
    ingredients: [ing("White Rice (cooked)", 220), ing("Peas (cooked)", 30), ing("Carrots", 30), ing("Vegetable Oil", 10), ing("Soy Sauce", 10)] },
  { name: "Chicken Fried Rice", cuisine: "global", serving_g: 350, kcal: 540, p: 24, c: 70, f: 16,
    ingredients: [ing("White Rice (cooked)", 220), ing("Chicken Breast (cooked)", 100), ing("Egg (whole)", 50), ing("Soy Sauce", 12)] },
  { name: "Pad Thai", cuisine: "global", serving_g: 350, kcal: 600, p: 22, c: 76, f: 22,
    ingredients: [ing("Rice Noodles (cooked)", 200), ing("Shrimp (cooked)", 80), ing("Peanuts", 15), ing("Egg (whole)", 50)] },
  { name: "Caesar Salad", cuisine: "global", serving_g: 250, kcal: 380, p: 14, c: 18, f: 28,
    ingredients: [ing("Lettuce", 150), ing("Parmesan Cheese", 20), ing("Bread (white slice)", 30), ing("Olive Oil", 15)] },
  { name: "Greek Salad", cuisine: "global", serving_g: 300, kcal: 280, p: 8, c: 14, f: 22,
    ingredients: [ing("Cucumber", 100), ing("Tomato", 100), ing("Cheddar Cheese", 40), ing("Olive Oil", 15)] },
  { name: "Garden Salad", cuisine: "global", serving_g: 250, kcal: 160, p: 4, c: 14, f: 10,
    ingredients: [ing("Lettuce", 100), ing("Tomato", 60), ing("Cucumber", 60), ing("Olive Oil", 10)] },
  { name: "Omelette (3 eggs)", cuisine: "global", serving_g: 180, kcal: 320, p: 22, c: 3, f: 24,
    ingredients: [ing("Egg (whole)", 150), ing("Butter", 8), ing("Cheddar Cheese", 20)] },
  { name: "Scrambled Eggs", cuisine: "global", serving_g: 150, kcal: 270, p: 18, c: 2, f: 21,
    ingredients: [ing("Egg (whole)", 120), ing("Butter", 8), ing("Whole Milk", 20)] },
  { name: "Steak (Sirloin)", cuisine: "global", serving_g: 200, kcal: 480, p: 50, c: 0, f: 30,
    ingredients: [ing("Beef (lean, cooked)", 180), ing("Butter", 8)] },
  { name: "Grilled Chicken Breast", cuisine: "global", serving_g: 180, kcal: 300, p: 56, c: 0, f: 7,
    ingredients: [ing("Chicken Breast (cooked)", 180)] },
  { name: "Grilled Salmon", cuisine: "global", serving_g: 180, kcal: 370, p: 36, c: 0, f: 24,
    ingredients: [ing("Salmon (cooked)", 180)] },
  { name: "Fish and Chips", cuisine: "global", serving_g: 350, kcal: 720, p: 30, c: 70, f: 36,
    ingredients: [ing("Cod (cooked)", 150), ing("Potato (boiled)", 180), ing("Vegetable Oil", 20)] },
  { name: "Turkey Sandwich", cuisine: "global", serving_g: 220, kcal: 380, p: 24, c: 42, f: 12,
    ingredients: [ing("Bread (whole wheat slice)", 80), ing("Chicken Breast (cooked)", 80), ing("Lettuce", 15), ing("Mayonnaise", 10)] },
  { name: "Club Sandwich", cuisine: "global", serving_g: 280, kcal: 580, p: 32, c: 46, f: 28,
    ingredients: [ing("Bread (white slice)", 90), ing("Chicken Breast (cooked)", 80), ing("Bacon", 25), ing("Cheddar Cheese", 25)] },
  { name: "PB&J Sandwich", cuisine: "global", serving_g: 130, kcal: 380, p: 12, c: 50, f: 16,
    ingredients: [ing("Bread (whole wheat slice)", 60), ing("Peanut Butter", 30), ing("Honey", 15)] },
  { name: "Veg Stir Fry", cuisine: "global", serving_g: 250, kcal: 220, p: 7, c: 24, f: 11,
    ingredients: [ing("Broccoli", 80), ing("Bell Pepper", 50), ing("Carrots", 50), ing("Vegetable Oil", 10), ing("Soy Sauce", 12)] },
  { name: "Chicken Stir Fry", cuisine: "global", serving_g: 300, kcal: 420, p: 32, c: 22, f: 22,
    ingredients: [ing("Chicken Breast (cooked)", 150), ing("Broccoli", 70), ing("Bell Pepper", 50), ing("Soy Sauce", 12), ing("Vegetable Oil", 10)] },
  { name: "Fried Chicken (2 pieces)", cuisine: "global", serving_g: 200, kcal: 550, p: 34, c: 18, f: 36,
    ingredients: [ing("Chicken Thigh (cooked)", 150), ing("Wheat Flour", 30), ing("Vegetable Oil", 20)] },
  { name: "Chicken Wings (6)", cuisine: "global", serving_g: 250, kcal: 620, p: 50, c: 4, f: 44,
    ingredients: [ing("Chicken Thigh (cooked)", 220), ing("Butter", 12)] },
  { name: "Pancakes (3)", cuisine: "global", serving_g: 200, kcal: 460, p: 10, c: 70, f: 14,
    ingredients: [ing("Wheat Flour", 80), ing("Whole Milk", 80), ing("Egg (whole)", 25), ing("Maple Syrup", 30)] },
  { name: "Waffles (2)", cuisine: "global", serving_g: 180, kcal: 480, p: 10, c: 64, f: 20,
    ingredients: [ing("Wheat Flour", 80), ing("Whole Milk", 60), ing("Egg (whole)", 25), ing("Butter", 15), ing("Maple Syrup", 25)] },
  { name: "French Toast (2 slices)", cuisine: "global", serving_g: 180, kcal: 380, p: 14, c: 48, f: 14,
    ingredients: [ing("Bread (white slice)", 80), ing("Egg (whole)", 50), ing("Whole Milk", 40), ing("Butter", 8)] },
  { name: "Oatmeal Bowl", cuisine: "global", serving_g: 300, kcal: 320, p: 11, c: 54, f: 7,
    ingredients: [ing("Oats (cooked)", 220), ing("Banana", 60), ing("Honey", 10)] },
  { name: "Yogurt Parfait", cuisine: "global", serving_g: 250, kcal: 280, p: 14, c: 42, f: 6,
    ingredients: [ing("Greek Yogurt", 180), ing("Strawberries", 40), ing("Honey", 15)] },
  { name: "Avocado Toast", cuisine: "global", serving_g: 180, kcal: 340, p: 9, c: 36, f: 18,
    ingredients: [ing("Bread (whole wheat slice)", 60), ing("Avocado", 80), ing("Egg (whole)", 50)] },
  { name: "Bagel with Cream Cheese", cuisine: "global", serving_g: 150, kcal: 380, p: 12, c: 56, f: 12,
    ingredients: [ing("Bread (white slice)", 100), ing("Cream Cheese", 40)] },
  { name: "Chicken Shawarma", cuisine: "global", serving_g: 300, kcal: 560, p: 32, c: 50, f: 24,
    ingredients: [ing("Flour Tortilla", 90), ing("Chicken Thigh (cooked)", 150), ing("Yogurt (curd)", 30), ing("Tomato", 30)] },
  { name: "Falafel Wrap", cuisine: "global", serving_g: 280, kcal: 540, p: 18, c: 60, f: 24,
    ingredients: [ing("Flour Tortilla", 90), ing("Chickpeas (cooked)", 100), ing("Lettuce", 30), ing("Olive Oil", 12)] },
  { name: "Gyro", cuisine: "global", serving_g: 300, kcal: 600, p: 28, c: 52, f: 28,
    ingredients: [ing("Flour Tortilla", 90), ing("Lamb (cooked)", 120), ing("Yogurt (curd)", 30)] },
  { name: "Hummus with Pita", cuisine: "global", serving_g: 200, kcal: 380, p: 12, c: 44, f: 16,
    ingredients: [ing("Chickpeas (cooked)", 100), ing("Olive Oil", 15), ing("Bread (whole wheat slice)", 60)] },
  { name: "Beef Stew", cuisine: "global", serving_g: 350, kcal: 420, p: 32, c: 24, f: 20,
    ingredients: [ing("Beef (lean, cooked)", 130), ing("Potato (boiled)", 100), ing("Carrots", 60)] },
  { name: "Chicken Noodle Soup", cuisine: "global", serving_g: 400, kcal: 240, p: 16, c: 28, f: 6,
    ingredients: [ing("Noodles (cooked)", 100), ing("Chicken Breast (cooked)", 70), ing("Carrots", 40)] },
  { name: "Tomato Soup", cuisine: "global", serving_g: 350, kcal: 180, p: 4, c: 24, f: 7,
    ingredients: [ing("Tomato", 200), ing("Heavy Cream", 20), ing("Butter", 6)] },
  { name: "Pork Dumplings (6)", cuisine: "global", serving_g: 180, kcal: 400, p: 16, c: 40, f: 18,
    ingredients: [ing("Wheat Flour", 80), ing("Pork (cooked)", 70), ing("Soy Sauce", 10)] },
  { name: "Chicken Pho", cuisine: "global", serving_g: 500, kcal: 380, p: 24, c: 52, f: 7,
    ingredients: [ing("Rice Noodles (cooked)", 200), ing("Chicken Breast (cooked)", 100)] },
  { name: "Beef Pho", cuisine: "global", serving_g: 500, kcal: 420, p: 26, c: 52, f: 11,
    ingredients: [ing("Rice Noodles (cooked)", 200), ing("Beef (lean, cooked)", 100)] },
  { name: "Sushi Bowl / Poke", cuisine: "global", serving_g: 400, kcal: 520, p: 28, c: 60, f: 16,
    ingredients: [ing("White Rice (cooked)", 200), ing("Salmon (cooked)", 120), ing("Avocado", 40), ing("Soy Sauce", 10)] },
  { name: "Mac and Cheese", cuisine: "global", serving_g: 300, kcal: 600, p: 22, c: 60, f: 28,
    ingredients: [ing("Pasta (cooked)", 180), ing("Cheddar Cheese", 60), ing("Whole Milk", 50), ing("Butter", 10)] },
  { name: "Risotto", cuisine: "global", serving_g: 300, kcal: 480, p: 12, c: 70, f: 14,
    ingredients: [ing("White Rice (cooked)", 220), ing("Parmesan Cheese", 25), ing("Butter", 12)] },
  { name: "Chicken Caesar Wrap", cuisine: "global", serving_g: 280, kcal: 520, p: 30, c: 42, f: 24,
    ingredients: [ing("Flour Tortilla", 90), ing("Chicken Breast (cooked)", 120), ing("Lettuce", 30), ing("Parmesan Cheese", 15)] },
  { name: "Beef Lasagna", cuisine: "global", serving_g: 350, kcal: 650, p: 32, c: 50, f: 32,
    ingredients: [ing("Pasta (cooked)", 150), ing("Ground Beef (cooked)", 130), ing("Mozzarella Cheese", 50), ing("Tomato Sauce", 80)] },
  { name: "Chicken Parmesan", cuisine: "global", serving_g: 320, kcal: 620, p: 42, c: 36, f: 32,
    ingredients: [ing("Chicken Breast (cooked)", 150), ing("Mozzarella Cheese", 50), ing("Pasta (cooked)", 100), ing("Tomato Sauce", 60)] },
  { name: "Eggs Benedict", cuisine: "global", serving_g: 250, kcal: 540, p: 26, c: 28, f: 36,
    ingredients: [ing("Bread (white slice)", 60), ing("Egg (whole)", 100), ing("Bacon", 30), ing("Butter", 15)] },
];

// Quick search helpers
const norm = (s: string) => s.toLowerCase();

export function searchIngredients(q: string, limit = 12): Ingredient[] {
  const n = norm(q.trim());
  if (!n) return INGREDIENTS.slice(0, limit);
  return INGREDIENTS.filter((i) => norm(i.name).includes(n) || i.tags?.some((t) => norm(t).includes(n))).slice(0, limit);
}

export function searchDishes(q: string, limit = 8): Dish[] {
  const n = norm(q.trim());
  if (!n) return DISHES.slice(0, limit);
  return DISHES.filter((d) => norm(d.name).includes(n)).slice(0, limit);
}

export function findIngredient(name: string): Ingredient | undefined {
  const n = norm(name);
  return INGREDIENTS.find((i) => norm(i.name) === n) ?? INGREDIENTS.find((i) => norm(i.name).includes(n));
}

export function findDish(name: string): Dish | undefined {
  const n = norm(name);
  return DISHES.find((d) => norm(d.name) === n) ?? DISHES.find((d) => norm(d.name).includes(n));
}
